name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ðŸ“Š Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      - name: ðŸ† Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          #plugin_achievements_only: >-
          #  polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          #  scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
      - name: â­ Star lists
        uses: lowlighter/metrics@latest
        with:
          filename: starlists.svg
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 5
          plugin_starlists_limit_repositories: 0
          plugin_starlists_limit_languages: 8
          plugin_starlists_shuffle_repositories: yes
          #plugin_starlists_only: TC39
      - name: ðŸˆ·ï¸ Most used languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 8
